apiVersion: v1
kind: Service
metadata:
  labels:
    run: sprinthive-bureau
    version: v1
  name: sprinthive-bureau-v1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: sprinthive-bureau
    version: v1
  type: ClusterIP